from customtkinter import *
from PIL import Image
from tkinter import *
screen = CTk()
screen.configure(fg_color = "#F0F0F0")
screen.geometry("800x500")
l1 = CTkLabel(screen,text = "New event",text_color = "black",fg_color = "#F0F0F0",font = ("bold",26))
l2 = CTkLabel(screen,text = "Great! Tell us a little about your event.",text_color = "black",fg_color = "#F0F0F0",font = ("thin",19))
l1.place(x = 30,y = 25)
l2.place(x = 30,y = 53)
f1 = CTkFrame(screen,fg_color = "white",height = 500,width = 800)
f1.place(x = 30,y = 95)
l3 = CTkLabel(f1,text = "Basic Information",text_color = "black",font = ("darkbold",23))
l4 = CTkLabel(f1,text = "* Event Title",text_color = "black",font = ("thin",19))
l3.place(x = 67,y = 9)
l4.place(x = 30,y = 50)
x1 = StringVar()
e1 = CTkEntry(f1,corner_radius = 5,text_color = "black",fg_color = "white",height = 35,width = 690,textvariable = x1)
l5 = CTkLabel(f1,text = "* Event Category",text_color = "black",font = ("thin",19))
e1.place(x = 30,y = 82)
l5.place(x = 30,y = 128)
x2 = StringVar()
opt1 = CTkComboBox(f1,variable = x2,height = 35,width = 200,corner_radius = 5,border_width = 1,border_color = "gray",fg_color = "white",text_color = "black",button_hover_color = "#7D6D6D",font = ("semibold",17),values = ["Educational","Business","Sports"])
opt1.place(x = 30,y = 165)
l6 = CTkLabel(f1,text = "Language",text_color = "black",font = ("thin",19))
l6.place(x = 280,y = 128)
x3 = StringVar()
opt2 =  CTkComboBox(f1,variable = x3,height = 35,width = 200,corner_radius = 5,border_width = 1,border_color = "gray",fg_color = "white",text_color = "black",button_hover_color = "#7D6D6D",font = ("semibold",17),values = ["English","Spanish","Hindi"])
opt2.place(x = 280,y = 165)
l7 = CTkLabel(f1,text = "Locale",text_color = "black",font = ("thin",19))
l7.place(x = 520,y = 128)
x4 = StringVar()
opt2 =  CTkComboBox(f1,variable = x4,height = 35,width = 200,corner_radius = 5,border_width = 1,border_color = "gray",fg_color = "white",text_color = "black",button_hover_color = "#7D6D6D",font = ("semibold",17),values = ["USA","INDIA","CANADA"])
opt2.place(x = 520,y = 165)
l8 = CTkLabel(f1,text = "* Planner First Name",text_color = "black",font = ("thin",19))
l8.place(x = 30,y = 220)
x5 = StringVar()
e2 = CTkEntry(f1,corner_radius = 5,text_color = "black",fg_color = "white",height = 35,width = 200,textvariable = x5)
e2.place(x = 30,y = 250)
l9 = CTkLabel(f1,text = "* Last Name",text_color = "black",font = ("thin",19))
l9.place(x = 280,y = 220)
x6 = StringVar()
e3 = CTkEntry(f1,corner_radius = 5,text_color = "black",fg_color = "white",height = 35,width = 200,textvariable = x6)
e3.place(x = 280,y = 250)
label1 = CTkLabel(f1,text = "* Planner Email",text_color = "black",font = ("thin",19))
label1.place(x = 520,y = 220)
x7 = StringVar()
e4 = CTkEntry(f1,corner_radius = 5,text_color = "black",fg_color = "white",height = 35,width = 200,textvariable = x7)
e4.place(x = 520,y = 250)
label2 = CTkLabel(screen,text = "This is just the start",text_color = "black",fg_color = "#F0F0F0",font = ("semibold",21))
label2.place(x = 900,y = 420)
label3 = CTkLabel(screen,text = "We can't wait to see what kind of event you put on!",text_color = "black",fg_color = "#F0F0F0",font = ("thin",13))
label3.place(x = 900,y = 450)
label4 = CTkLabel(f1,text = "Location",text_color = "black",fg_color = "white",font = ("darkbold",23))
label4.place(x = 67,y = 310)
label5 = CTkLabel(f1,text = "* Format",text_color = "black",font = ("thin",19))
label5.place(x = 30,y = 352)
screen.mainloop()